name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  tag: 0.3
  img_name: ${{ github.repository }}
  

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - id: read-docker-image-identifiers
        name: Read Docker Image Identifiers
        run: echo ::set-env name=IMAGE_REPOSITORY::$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')    
      - id: string
        uses: ASzc/change-string-case-action@v5
        with:
          string: XyZzY
      - id: step2
        run: echo ${{ steps.string.outputs.lowercase }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          registry: docker.pkg.github.com
          repository: ${{ env.IMAGE_REPOSITORY }}/env.img_name
          tags: ${{ env.img_name }}:latest,${{ env.img_name }}:${{ env.tag }}
